### PR TITLE
Add script for applying a policy to all vhosts

### PR DESCRIPTION
**Pull request by gerhard**
This is an iteration on:

```sh
#!/bin/bash
vhosts=( $( /var/vcap/jobs/rabbitmq-server/packages/rabbitmq-server/bin/rabbitmqctl list_vhosts ) )
length=${#vhosts[@]}
 
echo ${length}
for i in `seq 3 ${length}`;
do
        /var/vcap/jobs/rabbitmq-server/packages/rabbitmq-server/bin/rabbitmqctl set_policy -p ${vhosts[$i]} --priority 51 policy ".*" '{"x-max-length":100000}'
done
```

### CODE REVIEW

**Review by lukebakken — CHANGES_REQUESTED** [review]
I think we'd like to keep the contents of `scripts` as single-file deliverables, so I'd like to suggest executing the `list_vhosts` operation within `apply-policy-to-all-vhosts`

**Comment by gerhard** [comment]
Hmm, interesting observation.

To me, keeping concerns separate is just [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle). The reason why I find it suits scripts really well is because they call all sorts of external commands, meaning that they have many external dependencies, which makes testing hard. Even though mocking `curl` & `rabbitmqctl` in this case is possible via function shadowing, it tends to degrade quickly. With this approach, if we have many tiny scripts that do just one thing, we can find and fix bugs easier, as well as compose them in unexpected ways - [I've heard this somewhere before...](https://en.wikipedia.org/wiki/Unix_philosophy)

Also notice the `_` in `_vhosts`, which I use to signal the private nature. How well does this scale? You tell me: https://github.com/rabbitmq/rabbitmq-server-boshrelease/tree/master/jobs/rabbitmq-server/templates/bin

Let me know if you still feel the same after you've read my rant 😄

**Comment by lukebakken** [comment]
I would like scripts to be single files because that is simpler for an end user to grab via the raw-link & `curl` to then run locally. They don't have to worry about dependencies. I don't expect users to be cloning this entire repository to run a script, unlike the BOSH release repo.

If you would like to break commands out into sub-scripts, we should put them in a `lib/` directory to prevent cluttering `scripts/`

**Comment by gerhard** [comment]
I get it, you want easier distribution. Have you seen this? https://github.com/progrium/go-basher#motivation

**Comment by gerhard** [comment]
Ready for another round of QA

**Comment by lukebakken** [comment]
No, that's really slick! I'm also not opposed to re-writing stuff completely in Go, either 😸

**Comment by gerhard** [comment]
Well, that's the thing, we wouldn't need to rewrite anything:

> Combined with a tool like go-bindata, you can write programs that are part written in Go and part written in Bash that can be distributed as standalone binaries.

**Review by lukebakken — APPROVED** [review]
Tested as follows:

```
RABBITMQCTL=/home/lbakken/issues/rmq-generic-unix/rabbitmq_server-3.6.14/sbin/rabbitmqctl POLICY_PRIORITY=999 POLICY_APPLY_TO='queues' POLICY_NAME='my-test-policy' POLICY_PATTERN='.*' POLICY_DEFINITION='{"ha-mode":"nodes","ha-params":["rabbit@shostakovich"]}' ./apply-policy-to-all-vhosts 
Setting policy "my-test-policy" for pattern ".*" to "{\"ha-mode\":\"nodes\",\"ha-params\":[\"rabbit@shostakovich\"]}" with priority "999"
Setting policy "my-test-policy" for pattern ".*" to "{\"ha-mode\":\"nodes\",\"ha-params\":[\"rabbit@shostakovich\"]}" with priority "999"

$ /home/lbakken/issues/rmq-generic-unix/rabbitmq_server-3.6.14/sbin/rabbitmqctl -p / list_policies
Listing policies
/       my-test-policy  queues  .*      {"ha-mode":"nodes","ha-params":["rabbit@shostakovich"]} 999

$ /home/lbakken/issues/rmq-generic-unix/rabbitmq_server-3.6.14/sbin/rabbitmqctl -p vhost-two list_policies
Listing policies
vhost-two       my-test-policy  queues  .*      {"ha-mode":"nodes","ha-params":["rabbit@shostakovich"]} 999
```

**Comment by gerhard** [comment]
I am not convinced about `rabbitmqctl_cmd`. I think that all our support scripts should fail if the environment is not already configured to interact with RabbitMQ. I can think of the following pre-requisites for all scripts:

1. `rabbitmqctl` is in PATH
1. `erl` is in PATH
1. erlang cookie is set correctly

What do you think?

**Comment by lukebakken** [comment]
The variable does default to assuming the command is in the `PATH`. It's an env variable that is used in various client library test suites which is why I added it. Feel free to remove it and I can just alter `PATH` the next time I have to test something like this.

**Review by lukebakken — APPROVED** [review]

**Pull request merged**
