### PR TITLE
Implement different balancing algorithm

### PR DESCRIPTION
**Pull request by lukebakken**
Includes changes from #13 with refactoring to use bash features.

### CODE REVIEW

**Comment by lukebakken** [comment]
@manuvaldi - I'm setting up my three-node cluster using the following script:

[setup-test-env.sh.txt](https://github.com/rabbitmq/support-tools/files/2932115/setup-test-env.sh.txt)

After running that script, 1/2 the queues will be on one node, and 1/2 on another. The third will not have any. Running `rebalance-queue-masters` works great now on OS X and Linux, thank you for your input. I am using RabbitMQ 3.7.12 / Erlang 21.2.6

Please give it a try in your environment.

**Comment by manuvaldi** [comment]
> @manuvaldi - I'm setting up my three-node cluster using the following script:
> 
> [setup-test-env.sh.txt](https://github.com/rabbitmq/support-tools/files/2932115/setup-test-env.sh.txt)
> 
> After running that script, 1/2 the queues will be on one node, and 1/2 on another. The third will not have any. Running `rebalance-queue-masters` works great now on OS X and Linux, thank you for your input. I am using RabbitMQ 3.7.12 / Erlang 21.2.6
> 
> Please give it a try in your environment.

It works perfectly now!! Tested using RabbitMQ 3.6.3 / Erlang 18.3.4.7 with 3 nodes in Linux RHEL 7

**Comment by lukebakken** [comment]
@manuvaldi thank you for letting me know. FYI, please upgrade both RabbitMQ and Erlang - they are both very out-of-date. That version of Erlang in particular has known TCP issues.

**Comment by manuvaldi** [comment]
Thanks @lukebakken. I will take in account!

**Pull request merged**
