### PR TITLE
Queue name escaped to be used in regular expression

### PR DESCRIPTION
**Pull request by micdenny**
I found this script useful because `rabbitmq-queues rebalance` doesn't work on 3.8.0 and I can't update right now, the script is slow but works great except that the queue name is not escaped before it is used as a regular expression to se the policy, so I've fixed it.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@micdenny Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/support-tools&pullRequestId=23)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/support-tools&pullRequestId=23) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@micdenny Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/support-tools&pullRequestId=23)!

**Review by michaelklishin — APPROVED** [review]
Thank you!

**Review by lukebakken — COMMENTED** [review]
Could you please give an example of a queue name that causes problems? Thanks.

**Comment by micdenny** [comment]
> Could you please give an example of a queue name that causes problems? Thanks.

`test(123)` the parentheses
`test.abc` the dots has another meaning in regex, so that expression seems to works, but can also match `testZabc` or whatever char there's where there is the dot.

**Comment by lukebakken** [comment]
Great, thanks. Please see PR #24 where I take your commit and make sure that the script still passes `shellcheck`

**Pull request closed without merging**
